### ISSUE TITLE
Initializer Web project throwing error

### ISSUE THREAD

**Issue by nilanjan-cse** [SteeltoeOSS/InitializrWeb#129]
Initializer Web project throwing error.

<img width="942" alt="GITHUB-1" src="https://github.com/SteeltoeOSS/InitializrWeb/assets/15195713/50f72547-94ec-4580-871a-276fc36b911a">
<img width="871" alt="GITHUB-2" src="https://github.com/SteeltoeOSS/InitializrWeb/assets/15195713/f7d8bed9-6841-46c2-ac95-e55e36e711ec">

**Comment by nilanjan-cse** [comment]
Internet connection working properly. However , in network log 500 Internal Server Error throws on attempting to generate starter project

**Comment by TimHess** [comment]
Hi @nilanjan-cse,

Thanks for reporting the issue. Apparently something went wrong in initializr-service and requests to /uiconfig were coming back empty (the error message seems to be incorrect, sorry about that). The service has been restarted and it should be working now
