### ISSUE TITLE
Update site logos

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/InitializrWeb#37]
New Steeltoe logos have arrived

[https://app.zenhub.com/files/269465045/0180c751-9611-4530-b08d-d358f900c490/download](https://app.zenhub.com/files/269465045/0180c751-9611-4530-b08d-d358f900c490/download)ad)

**Comment by ccheetham** [comment]
@jkonicki The borders on these images are way too big to use on site

**Comment by jkonicki** [comment]
Logos have been updated, but we are not switching properly on light/dark mode.

**Comment by ccheetham** [comment]
I think this is a separate issue, a combination of SVG and JavaScript.
