### ISSUE TITLE
add Docker compose

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/InitializrWeb#5]
Add a docker compose file that:
* starts dependencies
* starts Steeltoe.Initializr.Starter

**Comment by jkonicki** [comment]
Run your own Initializr!
```
% git clone https://github.com/ccheetham/Initializr
% cd Initializr
% git checkout aks-deployment
% docker-compose up
```
For web, use http://localhost:8080/
For CLI, use http://localhost:1920/api
