### ISSUE TITLE
Add feedback link to the Initializr Issues board on the information screen

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/InitializrWeb#53]
Add a feedback link for our users.  Likely under the hamburger menu.

**Comment by ccheetham** [comment]
@jkonicki 
Need icons, one each for dark and light theme.

Presumably feedback should link to InitializrWeb repo?  In the absence of a generic Initializr site.

**Comment by jkonicki** [comment]
Why do you need icons?  Just add a line item under "What's new with Steeltoe?" like  "Leave Feedback" that links to InitializrWeb
